config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)' do
    get 'admin' => 'admin#index'

    get 'store/index'
    get 'questions' => 'static_pages#questions'
    get 'news' => 'static_pages#news'
    get 'contact' => 'static_pages#contact'
    get 'about' => 'static_pages#about'
    get 'terms' => 'static_pages#terms'
    get 'privacy' => 'static_pages#privacy'

    controller :sessions do
      get 'login' => :new
      post 'login' => :create
      delete 'logout' => :destroy
    end

    resources :users
    resources :orders
    resources :line_items
    resources :carts

    resources :products do
      get :who_bought, on: :member
    end

    root to: 'store#index', as: 'store', via: :all
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png">
  <link rel="apple-touch-icon" sizes="60x60" href="/apple-touch-icon-60x60.png">
  <link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png">
  <link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png">
  <link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png">
  <link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png">
  <link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png">
  <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon-180x180.png">
  <link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
  <link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
  <link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96">
  <link rel="icon" type="image/png" href="/android-chrome-192x192.png" sizes="192x192">
  <link rel="manifest" href="/manifest.json">
  <meta name="msapplication-TileColor" content="#603cba">
  <meta name="msapplication-TileImage" content="/mstile-144x144.png">
  <meta name="msapplication-config" content="/browserconfig.xml">
  <meta name="theme-color" content="#ffffff">

  <title><%= full_title(yield(:title)) %></title>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body class="<%= controller.controller_name %>">
  <div class="page-wrap">
    <div class="content">
    <div id="banner">
      <%= form_tag store_path, class: 'locale' do %>
        <%= select_tag 'set_locale',
                       options_for_select(LANGUAGES, I18n.locale.to_s),
                       onchange: 'this.form.submit()' %>
        <%= submit_tag 'submit' %>
        <%= javascript_tag "$('.locale input').hide()" %>
      <% end %>

      <%= @page_title || t('.title_html') %>
    </div>

    <div id="columns">
      <div id="side">
        <ul>
          <li><%= link_to t('.home_html'), store_path %></li>
          <li><%= link_to t('.questions_html'), questions_path %></li>
          <li><%= link_to t('.news_html'), news_path %></li>
          <li><%= link_to t('.contact_html'), contact_path %></li>
        </ul>

        <% if session[:user_id] %>
          <ul>
            <li><%= link_to 'Admin\'s Home', admin_path %></li>
            <li><%= link_to 'Orders', orders_path %></li>
            <li><%= link_to 'Products', products_path %></li>
            <li><%= link_to 'Users', users_path %></li>
          </ul>

          <%= button_to t('.logout_html'), logout_path, method: :delete, class: 'button',
                        data: {disable_with: t('.logging_out_html')} %>
        <% end %>

        <div id="cart">
          <% if @cart %>
            <%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
              <%= render @cart %>
            <% end %>
          <% end %>
        </div>
      </div>

      <div id="main">
        <%= yield %>
      </div>
    </div>
  </div>

  <div class="footer">
    <div class="links">
      <ul>
        <li><h3><%= t('.content_html') %></h3></li>
        <li><%= link_to t('.about_html'), about_path %></li>
        <li><%= link_to t('.contact_html'), contact_path %></li>
      </ul>
      <ul>
        <li><h3><%= t('.follow_html') %></h3></li>
        <li><a href="https://www.facebook.com">Facebook</a></li>
        <li><a href="https://twitter.com">Twitter</a></li>
      </ul>
      <ul>
        <li><h3><%= t('.legal_html') %></h3></li>
        <li><%= link_to t('.terms_html'), terms_path %></li>
        <li><%= link_to t('.privacy_html'), privacy_path %></li>
      </ul>
    </div>
    <hr>

    <div class="copyright">Michael Zelenyuk, 2015 -  <%= Time.now.year %></div>
  </div>
  </div>
</body>
</html>